# Generated by Django 3.1.7 on 2022-10-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('filesize', models.FloatField(default=0.0, verbose_name='用户文件大小')),
                ('stat', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userinformation',
            },
        ),
        migrations.CreateModel(
            name='updateFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputfile', models.FileField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinputfile', to='backadmin.userinformation')),
            ],
            options={
                'db_table': 'inputfile',
            },
        ),
        migrations.CreateModel(
            name='outputFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('fileid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatefileid', to='backadmin.updatefile')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroutfile', to='backadmin.userinformation')),
            ],
            options={
                'db_table': 'outputfile',
            },
        ),
    ]
