# Generated by Django 3.2.16 on 2022-11-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='生成的文件')),
            ],
            options={
                'db_table': 'mainfirstfile',
            },
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('filesize', models.FloatField(default=0.0, verbose_name='用户文件大小')),
                ('stat', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userinformation',
            },
        ),
        migrations.CreateModel(
            name='updateFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputfile', models.FileField(upload_to='%Y%m%d/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinputfile', to='backadmin.userinformation')),
            ],
            options={
                'db_table': 'inputfile',
            },
        ),
        migrations.CreateModel(
            name='secondFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secondoutput_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='二次对应生成的文件')),
                ('secondfileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondfile', to='backadmin.mainfile')),
            ],
            options={
                'db_table': 'secondfile',
            },
        ),
        migrations.CreateModel(
            name='outputFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('output_file', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('fileid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatefileid', to='backadmin.updatefile')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroutfile', to='backadmin.userinformation')),
            ],
            options={
                'db_table': 'outputfile',
            },
        ),
        migrations.AddField(
            model_name='mainfile',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainfileid', to='backadmin.updatefile'),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainoutfile', to='backadmin.userinformation'),
        ),
    ]
