# Generated by Django 3.1.7 on 2022-11-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='生成的文件')),
            ],
            options={
                'db_table': 'mainfirstfile',
            },
        ),
        migrations.AlterField(
            model_name='outputfile',
            name='output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='updatefile',
            name='inputfile',
            field=models.FileField(upload_to='%Y%m%d/'),
        ),
        migrations.CreateModel(
            name='secondFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secondoutput_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='二次对应生成的文件')),
                ('secondfileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondfile', to='backadmin.mainfile')),
            ],
            options={
                'db_table': 'secondfile',
            },
        ),
        migrations.AddField(
            model_name='mainfile',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainfileid', to='backadmin.updatefile'),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainoutfile', to='backadmin.userinformation'),
        ),
    ]
