# Generated by Django 3.1.7 on 2022-11-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backadmin', '0004_userinformation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefile',
            name='flag',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainfileid', to='backadmin.updatefile'),
        ),
    ]
