# Generated by Django 3.1.7 on 2022-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backadmin', '0005_auto_20221116_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='ipconfig',
            field=models.CharField(blank=True, default='192.168.10.102', max_length=225, null=True),
        ),
    ]
